project_id = "xtkcfhbsksoqbpnaciga"

[functions.turn-ice-servers]
verify_jwt = true
[functions.google-search]
verify_jwt = true

[functions.ai-research]
verify_jwt = true

[functions.ai-assistant]
verify_jwt = true
